management_gems:
  capistrano: capistrano
  piston: piston

gems:
  packet: packet
  chronic: chronic
  hpricot: hpricot
  unicode: unicode
  RedCloth: redcloth
  mime-types: mime/types
  memcache-client: memcache
  zoom: zoom
  libxml-ruby: libxml
  htmlentities: htmlentities

# we use a hacked version of oai gem for the timebeing
# included under vendor/gems
#  oai: oai

# these are problematic as gems depending on platform
# for example, rmagick on debian is best installed with
# sudo apt-get install librmagick-ruby1.8
libs:
  RMagick: RMagick

# memcached is truncated to "memcache" for compatibility with
# some systems' (Solaris10?) ps -c truncation amount
commands:
  Zebra: which zebrasrv
  Memcache Daemon: ps -Ac | grep memcache
  Unzip: which unzip
